//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebATM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public decimal TransAmount { get; set; }
        public System.DateTime TransDate { get; set; }
        public int TransTypeId { get; set; }
        public int AtmAccountId { get; set; }
    
        public virtual AtmAccount AtmAccount { get; set; }
        public virtual TransType TransType { get; set; }
    }
}
